algorithm:
  name: hls-landsat-tile
  description: Landsat to HLS tile processor
  code_repository: https://github.com/qlearwater/hls-landsat-tile

runtime:
  disk_space: 16GB # test mem needed
  docker_container_url: mas.maap-project.org/root/maap-workspaces/jupyterlab/pangeo:v4.3.0

command: >
  ./run.sh {mgrs_tile} {date}

inputs:
  - name: mgrs_tile
    type: string

  - name: date
    type: string